// Proposal B + capability rationale patch for NexGen_EA_V4.html
const fs = require('fs');
const filePath = 'NexGenEA/NexGen_EA_V4.html';
let content = fs.readFileSync(filePath, 'utf8');
let ok = 0, fail = 0;

function patch(label, oldStr, newStr) {
  if (content.includes(oldStr)) {
    content = content.replace(oldStr, newStr);
    console.log('OK   ' + label); ok++;
  } else {
    console.error('MISS ' + label); fail++;
  }
}

// ── 1. Remove aiAgents from profile objects ────────────────────────────────
patch('profile draft - remove aiAgents',
  "      systems: '5-7',\r\n      aiAgents: '2-3',\r\n      timeoutMs: 90000",
  "      systems: '5-7',\r\n      timeoutMs: 90000"
);
patch('profile deep - remove aiAgents',
  "      systems: '8-12',\r\n      aiAgents: '4-6',\r\n      timeoutMs: 180000",
  "      systems: '8-12',\r\n      timeoutMs: 180000"
);
patch('profile standard - remove aiAgents',
  "      systems: '6-10',\r\n      aiAgents: '3-5',\r\n      timeoutMs: 150000",
  "      systems: '6-10',\r\n      timeoutMs: 150000"
);

// ── 2. Replace Call 1 JSON schema + rules ─────────────────────────────────
const OLD_SCHEMA = `Return JSON:\r\n{"valueStreams":[{"name":""}],"capabilities":[{"name":"","domain":"Customer|Product|Operations|Risk|Finance|Technology|Support","valueStream":"","maturity":3,"strategicImportance":"low|medium|high","operationalCriticality":3,"dependsOnCapabilities":[""]}],"systems":[{"name":"","supportsCapability":"","criticality":"low|medium|high"}],"dataDomains":[{"name":""}],"aiAgents":[{"name":"","supportsCapability":"","criticality":"low|medium|high"}],"_meta":{"assumptions":["key assumption driving this architecture"],"confidence":0.0,"dataSources":["strategic intent","BMC","company description"],"keyDrivers":["top arch driver 1","top arch driver 2","top arch driver 3"]}}\r\nRules: \${profile.valueStreams} value streams, \${profile.capabilities} capabilities (each must have valueStream matching one generated value stream name), \${profile.systems} systems, \${profile.aiAgents} AI agents. dependsOnCapabilities must list exact names of other capabilities in this list.`;

const NEW_SCHEMA = `Return JSON:\r\n{"valueStreams":[{"name":"","purpose":"one sentence — what this value stream delivers to the customer or business"}],"capabilities":[{"name":"","domain":"Customer|Product|Operations|Risk|Finance|Technology|Support","valueStream":"","maturity":3,"strategicImportance":"low|medium|high","operationalCriticality":3,"dependsOnCapabilities":[""],"strategic_rationale":"one sentence — why this capability is required by the strategic ambition or a specific strategic theme","maturity_rationale":"one sentence — why the AS-IS maturity is rated at this level — what is actually weak or missing today"}],"systems":[{"name":"","supportsCapability":"","criticality":"low|medium|high","status":"active|legacy|planned"}],"_meta":{"assumptions":["key assumption driving this architecture"],"confidence":0.0,"dataSources":["strategic intent","BMC","company description"],"keyDrivers":["top arch driver 1","top arch driver 2","top arch driver 3"]}}\r\nRules:\r\n- \${profile.valueStreams} value streams with distinct purposes aligned to the strategic ambition\r\n- \${profile.capabilities} capabilities, each mapped to a value stream by exact name\r\n- \${profile.systems} systems — mark legacy systems clearly as status:'legacy'\r\n- strategic_rationale must reference a named strategic theme or the strategic ambition directly — never be generic\r\n- maturity_rationale must describe a concrete observable weakness, not a generic statement\r\n- dependsOnCapabilities: list exact names of other capabilities in this list that must exist first`;

patch('Call1 schema + rules', OLD_SCHEMA, NEW_SCHEMA);

// ── 3. Remove _showCFOSkeleton + _showBenchSkeleton + fix status message ──
patch('remove skeleton calls + fix status',
  "_setStep3Status('⏳ Step 1/3 — Building architecture structure...', 'active');\r\n  _showCFOSkeleton();\r\n  _showBenchSkeleton();",
  "_setStep3Status('⏳ Generating capability architecture...', 'active');"
);

// ── 4. Replace parallel calls block with heuristic-only approach ────────────
const OLD_PARALLEL = `    const capCount = (model.capabilities||[]).length;\r\n    _setStep3Status(\`Structure ready (\${capCount} capabilities) — enriching financials & benchmark...\`, 'active');\r\n    if (btnLabel) btnLabel.textContent = 'Enriching data...';\r\n    toast(\`Architecture structure ready ✓ (\${profile.mode} mode) — enriching financials & benchmark...\`);\r\n\r\n    // ── CALLS 2 + 3: PARALLEL ─────────────────────────────────────────\r\n    const industry = model.phase4Config?.industry || 'generic';\r\n    const [financialsResult, benchmarkResult] = await Promise.allSettled([\r\n      _enrichCapabilityFinancials(desc, _si3, model.capabilities),\r\n      _generateAIBenchmark(desc, _si3, industry)\r\n    ]);\r\n\r\n    // Apply financial enrichment\r\n    if (financialsResult.status === 'fulfilled' && Array.isArray(financialsResult.value)) {\r\n      const finMap = {};\r\n      financialsResult.value.forEach(f => { if (f.name) finMap[f.name.toLowerCase()] = f; });\r\n      model.capabilities = model.capabilities.map(c => {\r\n        const f = finMap[c.name.toLowerCase()];\r\n        if (!f) return c;\r\n        return { ...c,\r\n          fteHoursSavedPct: f.fteHoursSavedPct, invoiceVolumeImpactPct: f.invoiceVolumeImpactPct,\r\n          investmentEstimate: f.investmentEstimate, riskExposureEstimate: f.riskExposureEstimate,\r\n          revenueUpliftEstimate: f.revenueUpliftEstimate, sustainabilityImpactPct: f.sustainabilityImpactPct,\r\n          revenueExposure: f.revenueExposure, regulatoryExposure: f.regulatoryExposure,\r\n          confidence: f.confidence, assumptions: f.assumptions };\r\n      });\r\n    } else {\r\n      _applyHeuristicFinancials();\r\n    }\r\n    computeDerivedFinancials();\r\n    renderLayers(); // Refresh layer cards with financial badges\r\n    renderCFO();\r\n\r\n    // Apply AI benchmark\r\n    if (benchmarkResult.status === 'fulfilled' && benchmarkResult.value) {\r\n      model.aiBenchmark = benchmarkResult.value;\r\n    }\r\n    renderBenchmarking();\r\n\r\n    // Narrative fires last (uses financials)\r\n    generateNarrative();\r\n    updateWorkflowStepStates();\r\n    updateWorkflowProgress([1, 2, 3]); // Mark Steps 1-3 as completed\r\n\r\n    _setStep3Status(\`Done — \${capCount} capabilities · financials & benchmark ready\`, 'done');\r\n    if (btnLabel) btnLabel.textContent = isRefineArch ? 'Re-generate Architecture' : 'Generate Architecture';\r\n    toast('Architecture complete ✓ (' + profile.mode + ' mode)');`;

const NEW_PARALLEL = `    const capCount = (model.capabilities||[]).length;\r\n    updateWorkflowStepStates();\r\n    updateWorkflowProgress([1, 2, 3]); // Mark Steps 1-3 as completed\r\n\r\n    // Apply heuristic financials immediately — click "Enrich Financials (AI)" in CFO tab for AI-detailed estimates\r\n    _applyHeuristicFinancials();\r\n    computeDerivedFinancials();\r\n    renderLayers(); // Refresh layer cards with financial badges\r\n    renderCFO();\r\n\r\n    _setStep3Status(\`Done — \${capCount} capabilities ready\`, 'done');\r\n    if (btnLabel) btnLabel.textContent = isRefineArch ? 'Re-generate Architecture' : 'Generate Architecture';\r\n    toast(\`Architecture ready ✓ — \${capCount} capabilities (\${profile.mode} mode). Use "Enrich Financials" in CFO tab for AI estimates.\`);`;

patch('parallel calls block', OLD_PARALLEL, NEW_PARALLEL);

// ── 5. Add "Enrich Financials (AI)" button to CFO tab header ───────────────
patch('CFO tab header - add enrich button',
  "        <div class=\"flex items-center justify-between mb-3\">\r\n          <div class=\"text-xs font-bold text-slate-600\">CFO View \u2014 Financial Guardrails</div>\r\n          <div class=\"text-[10px] text-slate-400\">Business value is AI-estimated based on FTE & Volume drivers.</div>\r\n        </div>",
  "        <div class=\"flex items-center justify-between mb-3\">\r\n          <div class=\"text-xs font-bold text-slate-600\">CFO View \u2014 Financial Guardrails</div>\r\n          <div class=\"flex items-center gap-2\">\r\n            <span class=\"text-[10px] text-slate-400\">Heuristic estimates shown \u2014 use AI Enrich for capability-specific analysis.</span>\r\n            <button id=\"btn-enrich-financials\" onclick=\"enrichFinancialsAI()\" class=\"ea-btn ea-btn--primary\" style=\"font-size:10px;padding:4px 10px;\" title=\"Run AI-detailed financial analysis per capability\">\r\n              <span id=\"s-enrich\" class=\"spinner hidden\"></span>\r\n              <i class=\"fas fa-wand-magic-sparkles\"></i> Enrich Financials (AI)\r\n            </button>\r\n          </div>\r\n        </div>"
);

// ── 6. Add enrichFinancialsAI() function before computeDerivedFinancials ────
patch('add enrichFinancialsAI function',
  'function computeDerivedFinancials() {',
  `async function enrichFinancialsAI() {\r\n  if (!model.capabilities.length) { toast('Generate architecture first', true); return; }\r\n  const btn = document.getElementById('btn-enrich-financials');\r\n  const s = document.getElementById('s-enrich');\r\n  if (btn) btn.disabled = true;\r\n  if (s) s.classList.remove('hidden');\r\n  _showCFOSkeleton();\r\n  toast('Running AI financial analysis — estimating per-capability ROI, risk and savings...');\r\n  try {\r\n    const desc = document.getElementById('description').value.trim();\r\n    const si = model.strategicIntent || {};\r\n    const financial = await _enrichCapabilityFinancials(desc, si, model.capabilities);\r\n    if (Array.isArray(financial)) {\r\n      const finMap = {};\r\n      financial.forEach(f => { if (f.name) finMap[f.name.toLowerCase()] = f; });\r\n      model.capabilities = model.capabilities.map(c => {\r\n        const f = finMap[c.name.toLowerCase()];\r\n        if (!f) return c;\r\n        return { ...c,\r\n          fteHoursSavedPct: f.fteHoursSavedPct, invoiceVolumeImpactPct: f.invoiceVolumeImpactPct,\r\n          investmentEstimate: f.investmentEstimate, riskExposureEstimate: f.riskExposureEstimate,\r\n          revenueUpliftEstimate: f.revenueUpliftEstimate, sustainabilityImpactPct: f.sustainabilityImpactPct,\r\n          revenueExposure: f.revenueExposure, regulatoryExposure: f.regulatoryExposure,\r\n          confidence: f.confidence, assumptions: f.assumptions };\r\n      });\r\n      computeDerivedFinancials();\r\n      renderLayers();\r\n      renderCFO();\r\n      model.financialsEnriched = true;\r\n      toast('Financial analysis enriched with AI estimates ✓');\r\n      addAssistantMessage('**CFO Financial Analysis enriched** ✓\\n\\nCapability-specific AI estimates have replaced heuristic values. Review in the **CFO** tab.\\n\\n_Use "Recalculate" to adjust assumptions (FTE cost, risk factor, investment multiplier)._');\r\n    }\r\n  } catch(e) { toast('Error enriching financials: ' + e.message, true); _applyHeuristicFinancials(); renderCFO(); }\r\n  if (btn) btn.disabled = false;\r\n  if (s) s.classList.add('hidden');\r\n}\r\n\r\nfunction computeDerivedFinancials() {`
);

// ── 7. Add aiAgents generation inside generateTargetArch ────────────────────
const OLD_TARGET_CALL = `    const raw = await callAI('Return ONLY valid JSON array, no markdown.',\r\n      \`Based on this architecture and strategic intent, define the Target Architecture.\r\n\r\n\${siBlock}\r\nCapabilities to analyze: \${JSON.stringify(model.capabilities)}\r\n\r\nFor each capability, set a target maturity that is justified by the strategic direction — not just "one level up from current". High-strategic-importance capabilities aligned to strategic themes should have the most aggressive targets.\r\n\r\nReturn JSON array (ALL capabilities):\r\n[{\r\n  "name": "",\r\n  "currentMaturity": 2,\r\n  "targetMaturity": 4,\r\n  "domain": "",\r\n  "strategicImportance": "high|medium|low",\r\n  "action": "One specific action statement describing what must be done",\r\n  "enabler": "Platform|AI|Process|Data|People",\r\n  "strategicThemeLink": "Which strategic theme drives this uplift, or null"\r\n}]\`,\r\n      { taskType: 'heavy', temperature: 0.2 });\r\n    model.targetArch = JSON.parse(extractJSON(raw));\r\n    model.targetArchDone = true;`;

const NEW_TARGET_CALL = `    const [taResult, agentResult] = await Promise.allSettled([\r\n      callAI('Return ONLY valid JSON array, no markdown.',\r\n        \`Based on this architecture and strategic intent, define the Target Architecture.\r\n\r\n\${siBlock}\r\nCapabilities to analyze: \${JSON.stringify(model.capabilities)}\r\n\r\nFor each capability, set a target maturity that is justified by the strategic direction — not just "one level up from current". High-strategic-importance capabilities aligned to strategic themes should have the most aggressive targets.\r\n\r\nReturn JSON array (ALL capabilities):\r\n[{\r\n  "name": "",\r\n  "currentMaturity": 2,\r\n  "targetMaturity": 4,\r\n  "domain": "",\r\n  "strategicImportance": "high|medium|low",\r\n  "action": "One specific action statement describing what must be done",\r\n  "enabler": "Platform|AI|Process|Data|People",\r\n  "strategicThemeLink": "Which strategic theme drives this uplift, or null"\r\n}]\`,\r\n        { taskType: 'heavy', temperature: 0.2 }),\r\n      callAI('You are a senior AI architect. Return ONLY valid JSON array, no markdown.',\r\n        \`Define the TARGET STATE AI agents for this organisation based on the strategy and capability map.\r\n\r\n\${siBlock}\r\nCapabilities: \${JSON.stringify(model.capabilities.map(c=>({name:c.name, domain:c.domain, maturity:c.maturity, strategicImportance:c.strategicImportance})))}\r\n\r\nRules:\r\n- Generate 3-6 AI agents that are grounded in the strategic direction and this specific industry\r\n- Each agent must support a specific named capability from the list above\r\n- Be practical: RPA bots, ML models, NLP assistants, recommendation engines, decisioning systems\r\n- Only include agents that deliver clear, measurable business value\r\n\r\nReturn JSON array:\r\n[{"name":"","supportsCapability":"","criticality":"low|medium|high","agentType":"RPA|ML|NLP|Recommendation|Decisioning|Analytics","businessValue":"one sentence — what business outcome this agent delivers"}]\`,\r\n        { taskType: 'heavy', temperature: 0.2 })\r\n    ]);\r\n    model.targetArch = JSON.parse(extractJSON(taResult.status === 'fulfilled' ? taResult.value : '[]'));\r\n    if (agentResult.status === 'fulfilled') {\r\n      try {\r\n        model.aiAgents = JSON.parse(extractJSON(agentResult.value));\r\n        renderLayers(); // refresh AI agents layer\r\n      } catch(e) { console.warn('aiAgents parse failed', e); }\r\n    }\r\n    model.targetArchDone = true;`;

patch('generateTargetArch - add aiAgents', OLD_TARGET_CALL, NEW_TARGET_CALL);

fs.writeFileSync(filePath, content, 'utf8');
console.log(`\nResult: ${ok} OK, ${fail} MISS`);
